on:
  push
permissions:
  contents: write #see https://docs.github.com/actions/using-jobs/assigning-permissions-to-jobs

name: md5-CI-build

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    steps:
      - name: disable auto crlf
        uses: steve02081504/disable-autocrlf@v1
      - name: checkout
        uses: actions/checkout@v2
      - name: shiori-check
        uses: Taromati2/yaya-CI-check@v1
        with:
          shiori-path: ghost\master\yaya.dll
      - name: md5file-CI-build
        uses: Taromati2/ukagaka-mirror-md5-CI-build@v1
        with:
          build-mode: other
